name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check ./src/mod.ts

      - name: Run tests, coverage, create test report and badges
        run: deno task test

      - name: Setup Node / NPM
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@continuit'

      - name: Build npm package
        run: deno task publish_npm_dry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

